server:
  port: 9000

spring:
  datasource:
    url: jdbc:mysql://106.53.102.70:3306/breakfast-pi?characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false
    name: breakfast-pi
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: 106.53.102.70
    port: 6379
    database: 10
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0


mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

pagehelper:
  helperDialect: mysql
  reasonable: false
  supportMethodsArguments: true
  params: count=countSql

# for show executed sql
logging:
  level:
    com:
      ita:
        domain:
          mapper:
            debug
  file: log/logfile.log

mqtt:
  broker: tcp://broker.emqx.io:1883
  liveTime: 60
  topic: ita/breakfast
  connStr: fR0pWHACB35Y46StaLsT0A==
  clientId: mqttx_4a02f566

miniprogramer:
  appId: wxeb9fc8420790d4fd
  appSecret: f32d7217755c1df12d45b7bd34a78a38

aes:
  secret: ixHAvlnOMOGroRby

image:
  path: D:/usr/local/openresty/nginx/html/resources/
